const INIT_DATA="INIT_DATA"
const CHANGE_NUM="CHANGE_NUM"
const CHECK_ONOE="CHECK_ONOE"
const CHECKED_ALL="CHECKED_ALL"
const DELETE_DAT="DELETE_DAT"
export {
    INIT_DATA,
    CHANGE_NUM,
    CHECK_ONOE,
    CHECKED_ALL,
    DELETE_DAT
}